export default {
    ADVANCEMENT: 'advacement',
    ADVANCEMENT_TEAMS: 'advacement_teams',
    EMPLOYMENT: "employement",
    FINANCE: "finance",
    REPORTS: "reports",
    SETUP: "setup",
    TASK_INDIVIDUAL: 'task_individual',
    TASK_TEAMS: 'task_teams',
    TASK_COMPANY: 'task_company',
    ATTENDANCE_INDIVIDUAL: 'attendance_individual',
    ATTENDANCE_TEAMS: 'attendance_teams',
    ATTENDANCE_COMPANY: 'attendance_company',
    LEAVES_INDIVIDUAL: 'leave_individual',
    LEAVES_TEAMS: 'leaves_teams',
    LEAVES_COMPANY: 'leaves_company',
    POLICY: 'policy_company',
    POLICY_INDIVIDUAL: 'policy_individual',
    REQUESTS: 'requests',
    REQUESTS_INDIVIDUAL: 'requests_individual',
    DASHBOARD: 'dashboard_company',
    DASHBOARD_USER: 'dashboard_individual',
};