export default {
    ADVANCEMENT: 'advancement',
    EMPLOYMENT: "employement",
    FINANCE: "finance",
    REPORTS: "reports",
    SETUP: "setup",
    TASK_INDIVIDUAL: 'task_individual',
    TASK_TEAMS: 'task_teams',
    TASK: 'task_overall',
    ATTENDANCE_INDIVIDUAL: 'attendance_individual',
    ATTENDANCE_TEAMS: 'attendance_teams',
    ATTENDANCE: 'attendance_overall',
    LEAVES_INDIVIDUAL: 'leaves_individual',
    LEAVES_TEAMS: 'leaves_teams',
    LEAVES: 'leaves_overall',
    POLICY: 'policy',
    POLICY_INDIVIDUAL: 'policy_individual',
    REQUESTS: 'requests_overall',
    REQUESTS_MANAGER: 'requests_teams',
    REQUESTS_INDIVIDUAL: 'requests_individual',
    DASHBOARD: 'dashboard_company',
    DASHBOARD_USER: 'dashboard_individual',
};