export const PROGRAMME_LIST = "PROGRAMME_LIST";
export const PROGRAMME_LIST_FAC = "PROGRAMME_LIST_FAC";
export const PROGRAMME_LIST_FILTER = "PROGRAMME_LIST_FILTER";
export const EMPTY_PROGRAMME_LIST = "EMPTY_PROGRAMME_LIST";
export const SINGLE_PROGRAMME = "SINGLE_PROGRAMME";
export const ALL_MODULES = "ALL_MODULES";
export const EMPTY_PROGRAMME = "EMPTY_PROGRAMME";