export const CHANGE_TAB = 'CHANGE_TAB';
export const OVERALL_FINANCE = 'OVERALL_FINANCE';
export const OVERALL_FINANCE_LIST = 'OVERALL_FINANCE_LIST';
export const FINANACE_DETAIL = 'FINANACE_DETAIL';
