export const FORMS_LISTING = "FORMS_LISTING";
export const FORMS_FIELDS = "FORMS_FIELDS";
export const FORMS_DEPARTMENTS = "FORMS_DEPARTMENTS";
export const DEPARTMENT_APPROVAL = "DEPARTMENT_APPROVAL";
export const FORM_DETAILS = "FORM_DETAILS";
export const EMPTY_FORMS = "EMPTY_FORMS";