export const OVERALL_TASKS = "OVERALL_TASKS";
export const OVERALL_TASKS_WITH_STATUS = "OVERALL_TASKS_WITH_STATUS";
export const TEAM_TASKS = "TEAM_TASKS";
export const MY_TASKS = "MY_TASKS";
export const TEAM_TASKS_WITH_STATUS = "TEAM_TASKS_WITH_STATUS";
export const MY_AVAILABLE_LEAVES = "MY_AVAILABLE_LEAVES";
export const STATISTIC_LIST_ANNUAL = "STATISTIC_LIST_ANNUAL";
export const STATISTIC_LIST_REPLACEMENT = "STATISTIC_LIST_REPLACEMENT";
export const STATISTIC_LIST_UNPAID = "STATISTIC_LIST_UNPAID";
export const STATISTIC_BAR = "STATISTIC_BAR";
// export const STATISTIC_BAR_REPLACEMENT = "STATISTIC_BAR_REPLACEMENT";
// export const STATISTIC_BAR_UNPAID = "STATISTIC_BAR_UNPAID";


export const PROJECT_NAME = "PROJECT_NAME";
export const ADD_PROJECT_NAME = "ADD_PROJECT_NAME";
export const SINGLE_TASK_DETAIL = "SINGLE_TASK_DETAIL";
export const EMPTY_TASKS = "EMPTY_TASKS";
export const MY_TIMESHEETS = "MY_TIMESHEETS";
