export const OVERALL_TASKS = "OVERALL_TASKS";
export const OVERALL_TASKS_WITH_STATUS = "OVERALL_TASKS_WITH_STATUS";
export const TEAM_LEAVES = "TEAM_LEAVES";
export const MY_LEAVES = "MY_LEAVES";
export const EMPTY_ALL_LEAVES = "EMPTY_ALL_LEAVES";
export const TEAM_LEAVES_WITH_STATUS = "TEAM_LEAVES_WITH_STATUS";
export const MY_AVAILABLE_LEAVES = "MY_AVAILABLE_LEAVES";
export const STATISTIC_LIST = "STATISTIC_LIST";
export const STATISTIC_BAR = "STATISTIC_BAR";
export const SINGLE_LEAVE_DETAIL = "SINGLE_LEAVE_DETAIL";
export const APPLICATION_LEAVE_DETAIL = "APPLICATION_LEAVE_DETAIL";
export const LEAVE_TYPE = "LEAVE_TYPE";
export const LEAVE_DATA = "LEAVE_DATA";
export const LEAVE_APPROVERS = "LEAVE_APPROVERS";
export const CARRY_FORWARD_STATUS = "CARRY_FORWARD_STATUS";
export const ENTITLEMENT = "ENTITLEMENT";


export const PROJECT_NAME = "PROJECT_NAME";
export const ADD_PROJECT_NAME = "ADD_PROJECT_NAME";
export const EMPTY_TASKS = "EMPTY_TASKS";
export const MY_TIMESHEETS = "MY_TIMESHEETS";
