export const SCHOLARSHIP_LIST = "SCHOLARSHIP_LIST";
export const SCHOLARSHIP_TYPE_DROP = "SCHOLARSHIP_TYPE_DROP";
export const OUTSTANDING_PAYMENT = "OUTSTANDING_PAYMENT";
export const OUTSTANDING_TOTAL_PAYMENT = "OUTSTANDING_TOTAL_PAYMENT";
export const STUDENT_LIST = "STUDENT_LIST";
export const SCHOLARSHIP_SINGLE_DATA = "SCHOLARSHIP_SINGLE_DATA";