export const JOB_OPENING = 'JOB_OPENING';
export const JOBS_LIST = 'JOBS_LIST';
export const COMPANY_LIST = 'COMPANY_LIST';
export const SUITABLE_APPLICANTS = 'SUITABLE_APPLICANTS';
export const EMPTY_APPLICANTS = 'EMPTY_APPLICANTS';
export const OVERALL_FITINDEX = 'OVERALL_FITINDEX';
export const OVERALL_FITINDEX_CARD = 'OVERALL_FITINDEX_CARD';
export const ADVANCEMENT_DETAILS = 'ADVANCEMENT_DETAILS';

