export const REQUEST_LIST_PENDING = "REQUEST_LIST_PENDING";
export const REQUEST_LIST_ARCHIVE = "REQUEST_LIST_ARCHIVE";
export const REQUEST_LIST_YOUR_REQUEST = "REQUEST_LIST_YOUR_REQUEST";
export const FORMS_LIST = "FORMS_LIST";
export const REQUEST_DATA = "REQUEST_DATA";
export const FIELDS_LIST = "FIELDS_LIST";
export const EMPTY_REQUEST_DATA = "EMPTY_REQUEST_DATA";
export const EMPLOYEE_STATUS = "EMPLOYEE_STATUS";
