export const REQUEST_LIST_PENDING = "REQUEST_LIST_PENDING";
export const REQUEST_LIST_ARCHIVE = "REQUEST_LIST_ARCHIVE";
export const REQUEST_LIST_YOUR_REQUEST = "REQUEST_LIST_YOUR_REQUEST";
export const FORMS_LIST = "FORMS_LIST";