export const leaveFields = [
  {
    name: 'leave_type',
    label: 'Leave Type Name',
    req: true,
    placeholder: 'Type leave name',
    type: 'input',
    twocol: false,
    reqmessage: 'Please enter name',
  },
  {
    title: 'Avaliabale for the following',
    name: 'contract_type',
    label: 'Contract Type',
    req: true,
    placeholder: 'Select contract type',
    type: 'select',
    twocol: false,
    reqmessage: 'Please select type',
    options: [{ value: 'All', label: 'All' }],
  },
  {
    name: 'gender',
    label: 'Gender',
    req: true,
    placeholder: 'Select',
    type: 'select',
    twocol: false,
    colWidth: '0 1 230px',
    reqmessage: 'Gender required',
    options: [
      { label: 'Male', value: 'Male' },
      { label: 'Female', value: 'Female' },
      { label: 'All', value: 'All' },
    ],
  },
  {
    name: 'marital_status',
    label: 'Marital Status',
    req: true,
    placeholder: 'Select',
    type: 'select',
    colWidth: '0 1 230px',
    twocol: false,
    reqmessage: 'Marital Status required',
    options: [
      { label: 'Married', value: 'Married' },
      { label: 'Unmarried', value: 'Unmarried' },
      { label: 'All', value: 'All' },
    ],
  },
  {
    type: 'array',
    name: 'approvers',
    title: 'Approver',
    twocol: false,
    child: [
      {
        type: 'select',
        subheader: 'Approver',
        name: 'approver_select',
        req: false,
        placeholder: 'Please Select',
        twocol: false,
        options: [
          { label: 'Zain Kafeel', value: 'Zain Kafeel', id: 'HR-EMP-00004', doctp: 'HRMS Leave Type Approvers' },
          {
            label: 'Muhammad Waqas Baig',
            value: 'Muhammad Waqas Baig',
            id: 'HR-EMP-00005',
            doctp: 'HRMS Leave Type Approvers',
          },
          { label: 'sheeraz kaleem', value: 'sheeraz kaleem', id: 'HR-EMP-00001a', doctp: 'HRMS Leave Type Approvers' },
        ],
      },
    ],
  },
];
