const salaryInformation = [
  {
    type: 'select',
    name: 'currency_typeSalary',
    label: 'Salary Amount',
    placeholder: '',
    twocol: false,
    colWidth: '0 1 118px',

    options: [{ value: 'RM', label: 'RM' }],
  },
  {
    type: 'input',
    name: 'salary_amount',
    label: '',
    placeholder: 'Amount',
    twocol: false,
    req: true,
    reqmessage: 'Please enter amount',
    colWidth: '1 0 180px',
  },
  {
    type: 'select',
    name: 'payment_method',
    label: 'Payment Method',
    placeholder: 'Select Payment Method',
    twocol: true,
    req: true,
    reqmessage: 'Payment method required',
    options: [
      { value: 'Automatic Payment System (APS)', label: 'Automatic Payment System (APS)' },
      { value: 'Cash', label: 'Cash' },
      { value: 'Cheque', label: 'Cheque' },
    ],
  },
  {
    type: 'select',
    name: 'payment_frequency',
    label: 'Payment Frequency',
    placeholder: '',
    twocol: true,
    req: true,
    reqmessage: 'Payment frequency required',
    options: [
      { value: 'Daily', label: 'Daily' },
      { value: 'Weekly', label: 'Weekly' },
      { value: 'Biweekly', label: 'Biweekly' },
      { value: 'Monthly', label: 'Monthly' },
      { value: 'Quarterly', label: 'Quarterly' },
      { value: 'Annually', label: 'Annually' },
    ],
  },
  {
    type: 'select',
    name: 'payment_type',
    label: 'Payment Type',
    placeholder: '',
    twocol: true,
    options: [
      { value: 'Recurring', label: 'Recurring' },
      { value: 'Once', label: 'Once' },
    ],
  },
  {
    type: 'date',
    name: 'effective_date',
    label: 'Effective Date',
    placeholder: 'Please Select',
    twocol: true,
  },
  {
    type: 'select',
    name: 'tax_currency_type',
    label: 'Tax Ammount',
    placeholder: '',
    twocol: false,
    colWidth: '0 1 118px',
    options: [{ value: 'RM', label: 'RM' }],
  },
  {
    type: 'input',
    name: 'tax_amount',
    label: '',
    placeholder: '',
    twocol: false,
    colWidth: '1 0 180px',
  },
];

export { salaryInformation };
