export const TERM_LIST = "TERM_LIST";
export const CALENDAR_COURSE_LIST = "CALENDAR_COURSE_LIST";
export const TERM_DETAIL = "TERM_DETAIL";
export const COURSE_GROUP_TYPE = "COURSE_GROUP_TYPE";
export const TERM_DETAIL_PROGRAMME_LIST = "TERM_DETAIL_PROGRAMME_LIST";
export const PROGRAMME_DROP_LIST = "PROGRAMME_DROP_LIST";