export const OVERALL_ATTENDANCE = 'OVERALL_ATTENDANCE';
export const OVERALL_ATTENDANCE_LIST = 'OVERALL_ATTENDANCE_LIST';
export const TEAM_ATTENDANCE = 'TEAM_ATTENDANCE';

export const TEAM_ATTENDANCE_LIST = 'TEAM_ATTENDANCE_LIST';
export const MY_ATTENDANCE = 'MY_ATTENDANCE';
export const SINGLE_ATTENDANCE = 'SINGLE_ATTENDANCE';
export const TOTAL_ABSENT = 'TOTAL_ABSENT';
export const GET_EMPA_ATTENDANCE = 'GET_EMPA_ATTENDANCE';
