const addAllowences = [
  {
    type: 'select',
    label: 'Allowence Type',
    name: 'allowance_type',
    twocol: true,
    placeholder: 'Select Allwoence type',
    req: true,
    reqmessage: 'Account Number required',
    options: [
      { label: 'Children Education Allowance', value: 'Children Education Allowance' },
      { label: 'Hostel Allowance', value: 'Hostel Allowance' },
      { label: 'Transport Allowance', value: 'Transport Allowance' },
      { label: 'Outstation Allowance', value: 'Outstation Allowance' },
      { label: 'Daily Allowance', value: 'Daily Allowance' },
      { label: 'Uniform Allowance', value: 'Uniform Allowance' },
      { label: 'Academic/ Research Allowance', value: 'Academic/ Research Allowance' },
    ],
  },
  {
    type: 'select',
    label: 'Allowece Ammount',
    name: 'allowence_ammount_type',
    twocol: false,
    colWidth: '0 1 133px',
    options: [{ value: 'RM', label: 'RM' }],
  },
  {
    type: 'input',
    label: '',
    name: 'amount',
    twocol: false,
    placeholder: 'Enter Amount',
    req: true,
    reqmessage: 'Account Number required',
    colWidth: '1 0 180px',
  },
  {
    type: 'date',
    label: 'Date Given',
    name: 'date_given',
    req: true,
    reqmessage: 'Date required',
    twocol: true,
  },
  {
    type: 'upload',
    label: 'Upload Document (PDF 10MB max)',
    name: 'document',
    placeholder: 'Upload',
    req: true,
    reqmessage: 'File required',
    twocol: true,
  },
  {
    type: 'input',
    label: 'Description',
    name: 'description',
    placeholder: 'Descrition',
    req: true,
    reqmessage: 'Description required',
    twocol: true,
  },
];

export { addAllowences };
