export const TEAM_LIST = 'TEAM_LIST';
export const MEMBER_LIST = 'MEMBER_LIST';
export const TEAM_DETAILS = 'TEAM_DETAILS';
export const EMPLOYEE_DETAILS = 'EMPLOYEE_DETAILS';
export const EMPLOYEE_LIST = 'EMPLOYEE_LIST';
export const EMPLOYEE_CARD = 'EMPLOYEE_CARD';
