// export const workingHorFields = [
//   {
//     label: 'Template',
//     name: 'template_name',
//     type: 'input',
//     twocol: true,
//     placeholder: 'Type template name',
//     req: true,
//     reqmessage: 'Template Name required',
//   },
//   {
//     label: 'Company',
//     name: 'company',
//     type: 'select',
//     twocol: true,
//     placeholder: 'Select company',
//     req: true,
//     reqmessage: 'Company Name required',
//   },
//   {
//     subheader: 'Work Hours',
//     type: 'select',
//     name: 'work_hour_template',
//     label: 'Template',
//     placeholder: 'Please Select',
//     twocol: false,
//     colWidth: '1 0 100%',
//     req: true,
//     reqmessage: 'Please select',
//   },
//   {
//     type: 'array',
//     name: 'work_hour_template_detail',
//     twocol: false,
//     colWidth: '1 0 100%',
//     field: fields,
//     gap: [10, 10],
//     single: false,
//     noCard: true,
//     child: [
//       {
//         type: 'input',
//         name: 'day',
//         label: '',
//         static: true,
//         req: false,
//         twocol: false,
//         colWidth: '1 0 100px',
//       },
//       {
//         type: 'select',
//         name: 'work_hour_type',
//         label: '',
//         placeholder: 'Please Select',
//         req: true,
//         twocol: false,
//         colWidth: '1 0 100px',
//       },
//       {
//         type: 'input',
//         name: 'time_hour',
//         label: '',
//         req: true,
//         number: true,
//         min: 1,
//         max: 12,
//         arrow: false,
//         twocol: false,
//         colWidth: '0 1 70px',
//       },
//       {
//         type: 'input',
//         name: 'time_min',
//         label: '',
//         number: true,
//         arrow: false,
//         req: true,
//         min: 0,
//         max: 59,
//         twocol: false,
//         colWidth: '0 1 70px',
//       },
//       {
//         type: 'select',
//         name: 'time_type',
//         label: '',
//         placeholder: 'Select',
//         req: true,
//         twocol: false,
//         colWidth: '0 1 100px',
//       },
//       {
//         type: 'input',
//         name: 'work_hours',
//         label: '',
//         req: true,
//         number: true,
//         arrow: false,
//         min: 0,
//         max: 24,
//         placeholder: 'Please state',
//         twocol: false,
//         colWidth: '1 0 70px',
//       },
//     ],
//   },
// ];
